// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: protos/logger.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Log  string `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Time string `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *LogSaveRequest) Reset() {
	*x = LogSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_logger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSaveRequest) ProtoMessage() {}

func (x *LogSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSaveRequest.ProtoReflect.Descriptor instead.
func (*LogSaveRequest) Descriptor() ([]byte, []int) {
	return file_protos_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogSaveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogSaveRequest) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *LogSaveRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type LogSaveRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LogSaveRespone) Reset() {
	*x = LogSaveRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_logger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSaveRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSaveRespone) ProtoMessage() {}

func (x *LogSaveRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSaveRespone.ProtoReflect.Descriptor instead.
func (*LogSaveRespone) Descriptor() ([]byte, []int) {
	return file_protos_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogSaveRespone) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protos_logger_proto protoreflect.FileDescriptor

var file_protos_logger_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2a, 0x0a,
	0x0e, 0x4c, 0x6f, 0x67, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x37, 0x0a, 0x06, 0x4c, 0x6f, 0x67,
	0x67, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x0f,
	0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65,
	0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x65, 0x6f, 0x66, 0x66, 0x72, 0x65, 0x79, 0x2d, 0x61, 0x6e, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_logger_proto_rawDescOnce sync.Once
	file_protos_logger_proto_rawDescData = file_protos_logger_proto_rawDesc
)

func file_protos_logger_proto_rawDescGZIP() []byte {
	file_protos_logger_proto_rawDescOnce.Do(func() {
		file_protos_logger_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_logger_proto_rawDescData)
	})
	return file_protos_logger_proto_rawDescData
}

var file_protos_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_logger_proto_goTypes = []interface{}{
	(*LogSaveRequest)(nil), // 0: LogSaveRequest
	(*LogSaveRespone)(nil), // 1: LogSaveRespone
}
var file_protos_logger_proto_depIdxs = []int32{
	0, // 0: Logger.SaveLog:input_type -> LogSaveRequest
	1, // 1: Logger.SaveLog:output_type -> LogSaveRespone
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_logger_proto_init() }
func file_protos_logger_proto_init() {
	if File_protos_logger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_logger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_logger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogSaveRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_logger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_logger_proto_goTypes,
		DependencyIndexes: file_protos_logger_proto_depIdxs,
		MessageInfos:      file_protos_logger_proto_msgTypes,
	}.Build()
	File_protos_logger_proto = out.File
	file_protos_logger_proto_rawDesc = nil
	file_protos_logger_proto_goTypes = nil
	file_protos_logger_proto_depIdxs = nil
}
