version: "3"
services:
  server:
    build: ./server
    depends_on:
      - logger-service
      - randomjoke-service
    volumes:
      - ./server:/usr/src/server
    environment:
      - PORT=${SERVER_PORT}
      - GRPC_RANDOMJOKE_HOST=randomjoke-service:${RANDOMJOKE_PORT}
      - KAFKA_TOPIC=${KAFKATOPIC}
      - KAFKA_SERVER=kafka:${KAFKASERVER}
    restart: always
    networks:
      - my-net
        # ipv4_address: "192.168.96.3"
    scale: 3
  logger-service:
    build: ./logger
    volumes:
      - ./logger:/usr/src/logger
    environment:
      - KAFKA_TOPIC=${KAFKATOPIC}
      - KAFKA_SERVER=kafka:${KAFKASERVER}
      - KAFKA_GROUP_ID=${KAFKAGROUPID}
    restart: always
    depends_on:
      - kafka
    networks:
      my-net:
        ipv4_address: "192.168.96.20"
  randomjoke-service:
    build: ./randomjoke
    volumes:
      - ./randomjoke:/usr/src/randomjoke
    environment:
      - PORT=${RANDOMJOKE_PORT}
    ports:
      - "51051:${RANDOMJOKE_PORT}"
    restart: always
    networks:
      my-net:
        ipv4_address: "192.168.96.21"
  nginx:
    build: ./nginx
    ports:
      - "8080:${NGINX_PORT}"
    depends_on:
      - server
    networks:
      my-net:
        ipv4_address: "192.168.96.254"
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      my-net:
        ipv4_address: "192.168.96.100"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      my-net:
        ipv4_address: "192.168.96.101"
networks:
  my-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.96.0/24"
