version: "3"
services:
  server:
    build: ./server
    depends_on:
      - logger-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/usr/src/server
    environment:
      - PORT=${SERVER_PORT}
      - GRPC_LOGGER_HOST=logger-service:${LOGGER_PORT}
    restart: always
    networks:
      my-net:
        ipv4_address: "192.168.96.10"
  logger-service:
    build: ./logger
    ports:
      - "${LOGGER_PORT}:${LOGGER_PORT}"
    volumes:
      - ./logger:/usr/src/logger
    environment:
      - PORT=${LOGGER_PORT}
    restart: always
    networks:
      my-net:
        ipv4_address: "192.168.96.20"
networks:
  my-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.96.0/24"
