version: "3"
services:
  server:
    build: ./server
    depends_on:
      - logger-service
      - randomjoke-service
    # ports:
    #   - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/usr/src/server
    environment:
      - PORT=${SERVER_PORT}
      - GRPC_LOGGER_HOST=logger-service:${LOGGER_PORT}
      - GRPC_RANDOMJOKE_HOST=randomjoke-service:${RANDOMJOKE_PORT}
    restart: always
    networks:
      - my-net
    scale: 1
  logger-service:
    build: ./logger
    # ports:
    #   - "${LOGGER_PORT}:${LOGGER_PORT}"
    volumes:
      - ./logger:/usr/src/logger
    environment:
      - PORT=${LOGGER_PORT}
    restart: always
    networks:
      my-net:
        ipv4_address: "192.168.96.20"
  randomjoke-service:
    build: ./randomjoke
    # ports:
    #   - "${RANDOMJOKE_PORT}:${RANDOMJOKE_PORT}"
    volumes:
      - ./randomjoke:/usr/src/randomjoke
    environment:
      - PORT=${RANDOMJOKE_PORT}
    restart: always
    networks:
      my-net:
        ipv4_address: "192.168.96.30"
  nginx:
    build: ./nginx
    ports:
      - "3001:${NGINX_PORT}"
    depends_on:
      - server
    networks:
      - my-net
    restart: always
networks:
  my-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.96.0/24"
